name: 'Create Pull Request Action'
description: 'Create new Pull Request'
author: avdeev-dima-tutu
branding:
  icon: 'stop-circle'  
  color: 'white'
inputs:
  branch_from:
    description: 'Branch from'
    required: true
  branch_to:
    description: 'Branch to'
    required: true
  title:
    description: 'title'
    required: true
  access_token:
    description: 'Your GitHub Access Token, ie: secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
